### ISSUE TITLE
Getting the swap usage

### ISSUE THREAD

**Issue by idrissneumann** [stollcri/nmond#2]
Is it possible to provide a way to get the swap usage like the Linux implementation of nmon does ?

Here is an example of the nmon "memory usage" output (that contain the swap usage as well) on a Linux virtual machine:

<img width="528" alt="Screen Shot 2019-11-03 at 1 35 46 PM" src="https://user-images.githubusercontent.com/12884347/68085228-fac2ab00-fe3e-11e9-8aec-cbc9cc5e2873.png">

Thanks in advance.

**Comment by stollcri** [comment]
Added swap to the memory pane in [0.1.14](https://github.com/stollcri/nmond/releases/tag/0.1.14)
![Screen Shot 2019-11-05 at 12 36 55 AM](https://user-images.githubusercontent.com/2474948/68181202-808c4680-ff64-11e9-8d8f-69ec3b6da594.png)

**Comment by idrissneumann** [comment]
Thank you very much!
